AWSTemplateFormatVersion: "2010-09-09"
Description: All things infrastructure for my blog

Resources:

  StagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: says-quietly.jakegillespie.me
      WebsiteConfiguration:
        IndexDocument: index.html

  StagingBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref StagingBucket
      PolicyDocument:
        Statement:
        - Action:
          - "s3:GetObject"
          Effect: "Allow"
          Resource: !Join [ "", [ "arn:aws:s3:::", !Ref StagingBucket, "/*" ] ]
          Principal: "*"

  StagingSite:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - says-quietly.jakegillespie.me
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: S3-says-quietly.jakegillespie.me
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: "http2"
        Origins:
        - DomainName: says-quietly.jakegillespie.me.s3.amazonaws.com
          Id: S3-says-quietly.jakegillespie.me
          S3OriginConfig:
            OriginAccessIdentity: ""
        PriceClass: PriceClass_100

  StagingRoute:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName: !GetAtt StagingSite.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: Z24837ZZ5BAXFE  # Requires hosted zone as created by dot-infrastructure.
      Name: says-quietly.jakegillespie.me.
      Type: A
